version: "3.4"

services:
 nginx:
  container_name: nginx
  build: ./requirements/nginx/
  env_file:
      - .env
  networks:
        - private_network
  restart: unless-stopped
  ports:
          - "443:443"
  volumes:
           - wp_data:/var/www/html
  depends_on:
      - wordpress
 wordpress:
  container_name: wordpress
  env_file:
      - .env
  build: ./requirements/wordpress/ 
  #image: wordpress:php8.2-fpm-alpine
  networks:
      - private_network
  volumes:
          - wp_data:/var/www/html
  depends_on:
      - mariadb
 mariadb:
  container_name: mariadb
  build: ./requirements/mariadb/ 
  env_file:
      - .env
  volumes:
          - db_data:/var/lib/mysql
  networks:
      - private_network
  restart: always
volumes:
 wp_data:
  name: wordpress
  driver: local
  driver_opts:
    device: /home/atouati/data/wp
    o: bind
    type: none
 db_data:
  name: mariadb
  driver: local
  driver_opts:
    device: /home/atouati/data/db
    o: bind
    type: none
networks:
 private_network: